server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: a01043429904 # 3
    password: nivttdfmojoymhul    # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

cloud:
  aws:
    credentials:
      access-key: AKIARS47I7B5RBDXR5X4
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket:
        url: https://spring-test-hojun.s3.ap-northeast-2.amazonaws.com/
        name: spring-test-hojun
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR